package pom;

public class NewReward {

    public static class Locator {
        public static final String rwd_title_id = "title";
        public static final String rwd_regular_price_id = "reguler-price";
        public static final String rwd_offer_price_id = "offer-price";
        public static final String rwd_stock_id = "stock";
        public static final String shipping_id = "allowShipping";
        public static final String shipping_xpth = "//*[@id=\"shipping\"]/div[1]/label";
        public static final String noshipping_id = "notAllowShipping";
        public static final String noshipping_xpth = "//*[@id=\"shipping\"]/div[2]/label";
        public static final String rwd_img_id = "image";
        public static final String rwd_des_id = "describe";
        public static final String create_rwd_xpth = "//*[@id=\"addOfferModal\"]/div/div[2]/div/div/form/button";

        public static final String img_crp_xpth = "//*[@id=\"offerImageCropper\"]/div/div[2]/div/div/div[2]/div[2]/button[2]";
    }

    public static class Text{
        public static final String rwd_title_txt = "Headphone";
        public static final String rwd_regular_price_txt = "79.49";
        public static final String rwd_offer_price_txt = "50.49";
        public static final String rwd_stock_txt = "120";
        public static final String rwd_des_txt = "This is a reward product that is generated by an automation script.";
    }
}
